language: python
python:
  - "2.7"
  #- "3.4"

install: "pip install -r requirements.txt"
before_script:
  - "pep8 --ignore=E501 py_skiplist/"
# command to run tests
script: coverage run --source py_skiplist -m unittest discover tests "*_tests.py"

after_success:
  coveralls